### ISSUE TITLE
What is citizen developer expected to fill into "SObject Id Name" ?

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#529]
What does the pre-filled value `TwitterScreenName__c` even mean to him?

![create-integration](https://cloud.githubusercontent.com/assets/8707241/25472261/df9dc830-2b2a-11e7-976f-14723e1271c3.png)

**Comment by zregvart** [comment]
Just to fill in the background to help reason about this: Salesforce has a number of built in entities called Salesforce objects (SObjects), `Contact` being the one those that we use in this connector. SObjects are composed of fields, and they usually have Id, Name and so on.

For the purposes of the connector we needed a unique field that holds the value of the twitter user's handle, we named that field `TwitterScreenName`, the `__c` is added automatically by Salesforce to all customizations. This field is used in conjunction with the _upsert_ functionality to determine if the Contact exists in Salesforce or the existing one should be updated -- hence the name _Create/Update Contact_.

As to the labelling of the field, this could simply be something as easy as `Unique Salesforce field` or since we have the whole width of the screen `Unique identifier field in Salesforce`.

Ideally the connector would provide a number of options, for instance all unique fields that can be used for this purpose and not present their field name, but their field label which is intended for humans to see; and switch to field name in the background. I don't think we have this functionality at the moment: to support picking values out of a list with human readable labels (in this case field label) and map those to computer readable values (in this case field name).

In case of Salesforce this list of options is also dynamic, as you can add a custom field at any point to your Salesforce organization.

**Comment by jknetl** [comment]
I believe we should provide a description of the field directly in the UI. We shouldn't rely on the fact that a citizen developer will know that field with such name:

1. must be created in advance in salesforce
2. must be marked as "external ID" field in salesforce

I don't know much about salesforce so when I tried twitter to salesforce integration, I didn't create TwitterScreenName__c in salesforce. Then I started the integration and it  didn't work. So I looked at logs of the pod with integration and I saw such a statement:

```
07:35:01.108 [HttpClient@2043702205-20] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-tname-test-1-6nk0m-33667-1498721694729-0-3 on ExchangeId: ID-tname-test-1-6nk0m-33667-1498721694729-0-2). Exhausted after delivery attempt: 1 caught: org.apache.camel.component.salesforce.api.NoSuchSObjectException: {errors:[{"errorCode":"NOT_FOUND","message":"Provided external ID field does not exist or is not accessible: TwitterScreenName__c"}],statusCode:404}

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[flow1             ] [flow1             ] [twitter://timeline/mentions?delay=30000                                       ] [       779]
[flow1             ] [to1               ] [json:marshal                                                                  ] [         3]
[flow1             ] [to2               ] [atlas:mapping-step-2.json                                                     ] [       459]
[flow1             ] [to3               ] [json:marshal                                                                  ] [         2]
[flow1             ] [to4               ] [salesforce-upsert-contact                                                     ] [       295]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.camel.component.salesforce.api.NoSuchSObjectException: {errors:[{"errorCode":"NOT_FOUND","message":"Provided external ID field does not exist or is not accessible: TwitterScreenName__c"}],statusCode:404}
        at org.apache.camel.component.salesforce.internal.client.DefaultRestClient.createRestException(DefaultRestClient.java:118)
        at org.apache.camel.component.salesforce.internal.client.AbstractClientBase$1.onComplete(AbstractClientBase.java:208)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:405)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:287)
        at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1067)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1392)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:170)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:131)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:130)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:116)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
```

So I've created the the "TwitterScreenName__c" field in salesforce, but I got the same error once again. The reason was that I didn't mark the field as the external id flags (I marked it only as unique). So it took me a while to realize what is wrong. But without the log it would be really hard to find a cause.

So since we are targeting to citizen developers I think there should be a clear description what is required to be done manually in salesforce for SObject Id field with a given value.

**Comment by dongniwang** [comment]
I think an updated UI design is being worked on which will address this issue. 

@sjcox-rh 

https://github.com/syndesisio/syndesis-project/issues/16

**Comment by gashcrumb** [comment]
In theory this issue should be fixed once we figure out https://github.com/syndesisio/syndesis-ui/issues/868

**Comment by gashcrumb** [comment]
We figured out #868
