### ISSUE TITLE
URL for getting filter options is wrong

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#630]
@rhuss commented on [Fri Jul 21 2017](https://github.com/syndesisio/syndesis-rest/issues/453)

When initialising the form, the UI requests the wrong URL for get the options. In fact the URL has the format:

`/{connectorId}/actions/{actionId}/filters/options`

as the possible filter fields depend on the action / endpoint before.

![image](https://user-images.githubusercontent.com/99080/28450935-ba787cf0-6dea-11e7-953a-9c90e1e23f10.png)

**Comment by rhuss** [comment]
Actually the server error is 

```
2017-07-21 06:04:11.635 ERROR [-,1c65463b80776319,1c65463b80776319,false] 1 --- [  XNIO-3 task-8] .s.r.v.h.e.SyndesisServerExceptionMapper : RESTEASY003210: Could not find resource for full path: http://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations/filters/options

javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://syndesis-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations/filters/options
	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:138) ~[resteasy-jaxrs-3.1.3.Final.jar!/:3.1.3.Final]
	at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43) ~[resteasy-jaxrs-3.1.3.Final.jar!/:3.1.3.Final]
	at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48) ~[resteasy-jaxrs-3.1.3.Final.jar!/:3.1.3.Final]
```

which must not result in a 500 but a 404.

**Comment by kahboom** [comment]
@rhuss - Just an update that this issue should have been resolved with [this](https://github.com/syndesisio/syndesis-ui/pull/671) PR, but it is still returning a 500, both locally and on staging. Verified that the URL structure looks okay w/ @gashcrumb  .
