### ISSUE TITLE
can't start local syndesis-ui dev server

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#806]
```
$ yarn
$ yarn start
yarn start v0.27.5
$ yarn ng serve -- --ssl true --ssl-key localhost.key --ssl-cert localhost.crt --proxy-config proxy.conf.js
** NG Live Development Server is listening on localhost:4200, open your browser on https://localhost:4200 **
 10% building modules 4/4 modules 0 activeCannot read property 'upgrade' of undefined
TypeError: Cannot read property 'upgrade' of undefined
    at Server.<anonymous> (/home/jludvice/devel/redhat/ipaas/syndesis-ui/node_modules/webpack-dev-server/lib/Server.js:382:42)
    at Array.forEach (native)
    at new Server (/home/jludvice/devel/redhat/ipaas/syndesis-ui/node_modules/webpack-dev-server/lib/Server.js:381:19)
    at Class.run (/home/jludvice/devel/redhat/ipaas/syndesis-ui/node_modules/@angular/cli/tasks/serve.js:167:24)
    at check_port_1.checkPort.then.port (/home/jludvice/devel/redhat/ipaas/syndesis-ui/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

```
node --version
v6.11.2
```

**Comment by zregvart** [comment]
@jludvice you need to either [regenerate](https://github.com/syndesisio/syndesis-ui#ui-developer-quick-start) your `src/config.json` or use [`src/config.json.staging`](https://github.com/syndesisio/syndesis-ui/blob/master/src/config.json.staging) if you're running against staging.

**Comment by jludvice** [comment]
Thanks for hint @zregvart 

I'd expect something like `invalid content of config.json` error message thought.
How is developer supposed to know ` Cannot read property 'upgrade' of undefined` is related to `config.json` ?
