### ISSUE TITLE
Validate integration name input field

### ISSUE THREAD

**Issue by jknetl** [syndesisio/syndesis-ui#818]
Input field for integration name is not verified on the frontend. When you try to create integration with name "Twitter Mention -> Salesforce upsert contact" the UI will appear that integration has been created. However, the syndesis-rest will fail to deploy the integration.

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://syndesis-openshift-proxy.qe.svc/oapi/v1/namespaces/qe/imagestreams. Message: ImageStream "twitter-mention---salesforce-upsert-contact" is invalid: metadata.name: Invalid value: "twitter-mention---salesforce-upsert-contact": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "twitter-mention---salesforce-upsert-contact": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*", reason=FieldValueInvalid, additionalProperties={})], group=null, kind=ImageStream, name=twitter-mention---salesforce-upsert-contact, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=ImageStream "twitter-mention---salesforce-upsert-contact" is invalid: metadata.name: Invalid value: "twitter-mention---salesforce-upsert-contact": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:332) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:271) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:241) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:212) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:733) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:326) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:395) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation$2.apply(BaseOperation.java:364) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.fabric8.openshift.api.model.DoneableImageStream.done(DoneableImageStream.java:27) ~[kubernetes-model-1.0.67.jar!/:1.0.67]
        at io.syndesis.openshift.OpenShiftServiceImpl.ensureImageStreams(OpenShiftServiceImpl.java:132) ~[openshift-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
        at io.syndesis.openshift.OpenShiftServiceImpl.lambda$create$2(OpenShiftServiceImpl.java:52) ~[openshift-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
        at io.fabric8.kubernetes.client.WithRequestCallable.call(WithRequestCallable.java:35) ~[kubernetes-client-2.2.13.jar!/:na]
        at io.syndesis.openshift.OpenShiftServiceImpl.create(OpenShiftServiceImpl.java:50) ~[openshift-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
        at io.syndesis.controllers.integration.online.ActivateHandler.createOpenShiftResources(ActivateHandler.java:215) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
        at io.syndesis.controllers.integration.online.ActivateHandler.execute(ActivateHandler.java:120) ~[controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
        at io.syndesis.controllers.integration.IntegrationController.lambda$callStatusChangeHandler$10(IntegrationController.java:173) [controllers-0.1-SNAPSHOT.jar!/:0.1-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]


```

**Comment by gashcrumb** [comment]
@rhuss wonder if we need server-side validation for this field or just having a regex in the frontend will be good enough?

**Comment by zregvart** [comment]
I don't think we can remove that one, it comes pre-packaged in fabric8 kubernetes client 😿

**Comment by gashcrumb** [comment]
Maybe we just need to decouple the name exposed to the user from the backend more?  Actually the generated name looks okay other than maybe it doesn't like the `---` characters like that...

**Comment by zregvart** [comment]
I think we can close this as it is entirely a backend issue.

see syndesisio/syndesis-rest#537

**Comment by gashcrumb** [comment]
Makes sense, thanks!
